### ISSUE TITLE
amiibo server throws cert error

### ISSUE THREAD

**Issue by lukebelliveau** [giamir/react-future#1]
..which breaks the suspense example. This might be overkill, but I'll deploy [this](https://gist.github.com/lukebelliveau/13b295fd6636cc9ac73571138319915f) to heroku and point the app to that if you're interested.

**edit**: it works just fine now, maybe my experience was just a fluke?

**Comment by giamir** [comment]
I switched back to http; that's probably why you don't experience the issue anymore.
I think it's ok to don't encrypt for now.
